# A configuration for small problem
---

models:
  - name: "test"
    gens: 5

  - name: "run 1"
    gens: 100

  - name: "run 2"
    gens: 200


data:
  - name: "test" # 0
    max_hop: 0

  - name: "small" # 1
    max_hop: 0

  - name: "ept_init" # 2
    max_hop: 0

  - name: "ept_efficiency" # 3
    max_hop: 0

  - name: "ept_scalability" # 4
    max_hop: 0

  - name: "ept_sparsity" # 5
    max_hop: 0

  - name: "params_selection" # 6
    max_hop: 0

  - name: "tiny" # 7
    max_hop: 0

  - name: "ept_terrain" # 8
    max_hop: 0

  - name: "ept_radius" # 9
    max_hop: 0


encoding:
  - name: "netkeys"  # 0
    init_method: "DCPrimRST"
    cro_prob: 0.7
    cro_di: 5
    mut_prob: 0.05
    mut_di: 0.20
    alpha: 2
    beta: 6

  - name: "netkeys"  # 1
    init_method: "DCPrimRST"
    cro_prob: 0.9
    cro_di: 20
    mut_prob: 0.1
    mut_di: 5
    alpha: 2
    beta: 6

  - name: "kruskal"  # 2
    init_method: "DCPrimRST"
    cro_prob: 0.9
    mut_prob: 0.5

  - name: "binary" # 3
    init_method: "DCPrimRST"
    cro_prob: 0.9
    cro_pe: 0.5
    mut_prob: 0.1

  - name: "prim"  # 4
    init_method: "DCPrimRST"
    cro_prob: 0.9
    mut_prob: 0.5
    
  - name: "mprim"  # 5
    init_method: "DCPrimRST"
    cro_prob: 0.9
    mut_prob: 0.5

  - name: "prufer"  # 6
    init_method: "DCPrimRST"
    cro_prob: 0.9
    mut_prob: 0.5

  - name: "hmoea"
    init_method: "DCPrimRST"
    cro_prob: 0.8
    mut_prob: 0.1

  - name: "mprim3"
    init_method: "DCPrimRST"
    cro_prob: 0.5
    mut_prob_a: 0.5
    mut_prob_b: 0.5

  - name: "mprim4"
    init_method: "DCPrimRST"
    cro_prob: 0.5
    mut_prob_a: 0.6
    mut_prob_b: 0.4


algorithm:
  - name: "nsgaii"  # 0
    pop_size: 100
    slt_size: 100
    tournament_size: 2

  - name: "nsgaii"  # 1
    pop_size: 100
    slt_size: 100
    tournament_size: 5

  - name: "nsgaii"  # 2
    pop_size: 300
    slt_size: 300
    tournament_size: 2

  - name: "nsgaii"  # 3
    pop_size: 300
    slt_size: 300
    tournament_size: 4

  - name: "moead"  # 5
    pop_size: 41
    slt_size: 100



